
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CMD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CMD` ;

-- -----------------------------------------------------
-- Schema CMD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CMD` DEFAULT CHARACTER SET utf8 ;
USE `CMD` ;

-- -----------------------------------------------------
-- Table `CMD`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMD`.`USERS` ;

CREATE TABLE IF NOT EXISTS `CMD`.`USERS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(100) NOT NULL,
  `MAIL` VARCHAR(45) NULL,
  `CTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMD`.`REPOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMD`.`REPOS` ;

CREATE TABLE IF NOT EXISTS `CMD`.`REPOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `FK_USERS` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_REPOS_USERS1_idx` (`FK_USERS` ASC),
  CONSTRAINT `fk_REPOS_USERS1`
    FOREIGN KEY (`FK_USERS`)
    REFERENCES `CMD`.`USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMD`.`DOCS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMD`.`DOCS` ;

CREATE TABLE IF NOT EXISTS `CMD`.`DOCS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `CONTENT` TEXT NULL,
  `USERS` VARCHAR(100) NULL,
  `CTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CUSER` VARCHAR(45) NULL,
  `UUSER` VARCHAR(45) NULL,
  `FK_REPOS` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DOCS_REPOS1_idx` (`FK_REPOS` ASC),
  CONSTRAINT `fk_DOCS_REPOS1`
    FOREIGN KEY (`FK_REPOS`)
    REFERENCES `CMD`.`REPOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMD`.`HISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMD`.`HISTORY` ;

CREATE TABLE IF NOT EXISTS `CMD`.`HISTORY` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `CONTENT` TEXT NULL,
  `HASH` VARCHAR(100) NULL,
  `CTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `FK_DOCS` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_HISTORY_DOCS_idx` (`FK_DOCS` ASC),
  CONSTRAINT `fk_HISTORY_DOCS`
    FOREIGN KEY (`FK_DOCS`)
    REFERENCES `CMD`.`DOCS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `CMD`;

DELIMITER $$

USE `CMD`$$
DROP TRIGGER IF EXISTS `CMD`.`USERS_BIR` $$
USE `CMD`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cmd`.`USERS_BIR` BEFORE INSERT ON `users` FOR EACH ROW
BEGIN
 SET NEW.CTIME = CURRENT_TIMESTAMP;
 SET NEW.UTIME = CURRENT_TIMESTAMP;
END$$


USE `CMD`$$
DROP TRIGGER IF EXISTS `CMD`.`USERS_BUR` $$
USE `CMD`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cmd`.`USERS_BUR` BEFORE UPDATE ON `users` FOR EACH ROW
BEGIN
 SET NEW.UTIME = CURRENT_TIMESTAMP;
END$$


USE `CMD`$$
DROP TRIGGER IF EXISTS `CMD`.`DOCS_BIR` $$
USE `CMD`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cmd`.`DOCS_BIR` BEFORE INSERT ON `docs` FOR EACH ROW
BEGIN
 SET NEW.CTIME = CURRENT_TIMESTAMP;
 SET NEW.UTIME = CURRENT_TIMESTAMP;
END$$


USE `CMD`$$
DROP TRIGGER IF EXISTS `CMD`.`DOCS_BUR` $$
USE `CMD`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cmd`.`DOCS_BUR` BEFORE UPDATE ON `docs` FOR EACH ROW
BEGIN
 SET NEW.UTIME = CURRENT_TIMESTAMP;
END$$


USE `CMD`$$
DROP TRIGGER IF EXISTS `CMD`.`HISTORY_BIR` $$
USE `CMD`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cmd`.`HISTORY_BIR` BEFORE INSERT ON `history` FOR EACH ROW
BEGIN
 SET NEW.CTIME = CURRENT_TIMESTAMP;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
